### ISSUE TITLE
Python Kernel Crashes While Running stand_alone_simple_profile

### ISSUE THREAD

**Issue by chriscourtin** [hoburg/d8#54] opened 2017-04-19 17:25 UTC
I'm trying to run the stand_alone_simple_profile.py file, but it is causing my python kernel to crash.  Has this issue been seen before?

I'm running the program in Jupyter notebook installed through Anaconda on windows.  Simpler GP models are running in the same environment.

sys.version output:  
2.7.13 |Anaconda custom (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]

Error message: 

Beginning signomial solve.
Using solver 'cvxopt'
Solving for 134 variables.
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  1.2177e+02  3e+02  1e+00  1e+00

The kernel appears to have died. It will restart automatically.

**Comment by mayork** [comment] 2017-04-19 17:30
I was at Aurora earlier and ran the file successfully on my machine in an iPython notebook

**Comment by ntvarney** [comment] 2017-04-19 19:10
I am having the same (or very similar) error running in Spyder using the same anaconda version as Chris. 

Error message:
Using solver 'cvxopt'
Solving for 138 variables.

Kernel died, restarting

Kernel died, restarting

**Comment by chriscourtin** [comment] 2017-04-19 19:44
Update: this issues goes away when the signomial constraints are removed

**Comment by bqpd** [comment] 2017-04-19 20:54
(@mayork, this looks like it might be a cvxopt issue)

**Comment by mayork** [comment] 2017-04-19 20:55
I solved with cvxopt on my machine earlier today

**Comment by bqpd** [comment] 2017-04-19 21:01
okay, hmm. An unexplained restart sounds like a C segmentation fault, maybe through a numerical error in BLAS caused by some high-precision signomial approx?

**Comment by chriscourtin** [comment] 2017-04-19 21:42
@bqpd strangely I get an import error on Vectorize when running from the windows command line, which does not occur when running inside the Anaconda environment (either through jupyter notebook, spyder, or qtconsole)

**Comment by bqpd** [comment] 2017-04-19 22:07
Could you print that error here? (it may need to be done from the anaconda command line so that it has the same python install as the notebook)

**Comment by chriscourtin** [comment] 2017-04-19 22:15
When running from windows command line:

C:\Users\courtin.christopher\Documents\Projects\LEARN3\d8-master>python stand_alone_simple_profile.py
Traceback (most recent call last):
  File "stand_alone_simple_profile.py", line 5, in <module>
    from gpkit import Vectorize
ImportError: cannot import name Vectorize

When running from anaconda command line: 
Beginning signomial solve.
Using solver 'cvxopt'
Solving for 134 variables.
     pcost       dcost       gap    pres   dres
 0:  0.0000e+00  1.2177e+02  3e+02  1e+00  1e+00

Kernel died, restarting


 
Kernel died, restarting

**Comment by bqpd** [comment] 2017-04-20 04:31
hmm, those `Kernel died, restarting` errors generally indicate ipython is being run. are you running  `python stand_alone_simple_profile.py` on the anaconda command prompt? When you run `python`  to drop you into the REPL (with the `>>>` prompt) what does it say your python version/bitness is?

**Comment by bqpd** [comment] 2017-04-20 04:33
My current guess is that 1) there's a system install of python that doesn't have gpkit installed, causing the import error at the regular command prompt and 2) there's some segmentation fault that cvxopt/libblas are causing that the ipython notebook does a bad job of showing to the user.

**Comment by chriscourtin** [comment] 2017-04-20 14:40
@bqpd you're right i was runningfrom ipython.  running through the anaconda command prompt gives the same error command line output : 

Beginning signomial solve.
Using solver 'cvxopt'
Solving for 134 variables.
pcost dcost gap pres dres
0: 0.0000e+00 1.2177e+02 3e+02 1e+00 1e+00

and then a popup saying python.exe died. This points to a log file that seems to indicate that lapack is crashing.   I'm running numpy version 1.11.3 and scipy version 0.18.1

-<WERReportMetadata>


-<OSVersionInformation>

<WindowsNTVersion>6.1</WindowsNTVersion>

<Build>7601 Service Pack 1</Build>

<Product>(0x30): Windows 7 Professional</Product>

<Edition>Professional</Edition>

<BuildString>7601.23714.amd64fre.win7sp1_ldr.170307-1800</BuildString>

<Revision>1130</Revision>

<Flavor>Multiprocessor Free</Flavor>

<Architecture>X64</Architecture>

<LCID>1033</LCID>

</OSVersionInformation>


-<ParentProcessInformation>

<ParentProcessId>18584</ParentProcessId>

<ParentProcessPath>C:\Windows\System32\cmd.exe</ParentProcessPath>

<ParentProcessCmdLine>"C:\Windows\System32\cmd.exe" "/K" C:\ProgramData\Anaconda2\Scripts\activate.bat C:\ProgramData\Anaconda2</ParentProcessCmdLine>

</ParentProcessInformation>


-<ProblemSignatures>

<EventType>APPCRASH</EventType>

<Parameter0>python.exe</Parameter0>

<Parameter1>0.0.0.0</Parameter1>

<Parameter2>58583522</Parameter2>

<Parameter3>lapack.pyd</Parameter3>

<Parameter4>0.0.0.0</Parameter4>

<Parameter5>561b95d5</Parameter5>

<Parameter6>c0000005</Parameter6>

<Parameter7>0000000000021f80</Parameter7>

</ProblemSignatures>


-<DynamicSignatures>

<Parameter1>6.1.7601.2.1.0.256.48</Parameter1>

<Parameter2>1033</Parameter2>

<Parameter22>f72a</Parameter22>

<Parameter23>f72aa61801e749011df12f186d93bfd6</Parameter23>

<Parameter24>b087</Parameter24>

<Parameter25>b087d7f90696f62c967d9f457afd46f5</Parameter25>

</DynamicSignatures>


-<SystemInformation>

<MID>4982AF74-6366-4ACF-8FA6-6C46D9CC92DF</MID>

<MarkerFile>1028_Dell_LAT_E7470</MarkerFile>

<SystemManufacturer>Dell Inc.</SystemManufacturer>

<SystemProductName>Latitude E7470</SystemProductName>

<BIOSVersion>1.1.6</BIOSVersion>

</SystemInformation>

</WERReportMetadata>

**Comment by bqpd** [comment] 2017-04-20 15:43
In particular we can see that the crash is occuring in `lapack.pyd` at an offset `0000000000021f80` from the start of the file...so this seems to be an error of that particular cvxopt binary. How did you install cvxopt, and what's the output of `pip show cvxopt`?

I'll try to get a Windows machine to reproduce those numbers, but in the meantime you might want to try reinstalling cvxopt using `conda install -f cvxopt`, on the off-chance your current binary suffered some corruption on-disk or during the download process.

**Comment by bqpd** [comment] 2017-04-20 15:45
The fact that @ntvarney is seeing a similar issue does point to it being a problem with that particular conda binary, though; maybe try `conda install -c conda-forge cvxopt=1.1.9` to see if that works.

**Comment by chriscourtin** [comment] 2017-04-20 15:55
>pip show cvxopt: 
Name: cvxopt
Version: 1.1.8
Summary: Convex optimization package
Home-page: http://cvxopt.org
Author: M. Andersen, J. Dahl, and L. Vandenberghe
Author-email: martin.skovgaard.andersen@gmail.com, dahl.joachim@gmail.com, vande
nbe@ee.ucla.edu
License: GNU GPL version 3
Location: c:\programdata\anaconda2\lib\site-packages\cvxopt-1.1.8-py2.7-win-amd6
4.egg
Requires:


Running the conda install -f command didn't change anything when run from the anaconda command window.   

It doesn't look like there is a win-64 compatible version of cvxopt 1.1.9.  I'll try setting this up in Linux to see if gets around the issue.

**Comment by bqpd** [comment] 2017-04-20 16:27
Oh, is that conda-forge 1.1.9 package not for Windows?

**Comment by bqpd** [comment] 2017-04-20 16:28
@mayork, let's meet up next week and trying running this on ECOS

**Comment by mayork** [comment] 2017-04-20 16:36
sounds good, just name a time

**Comment by mayork** [comment] 2017-04-28 14:28
@chriscourtin was this resolved?

**Comment by chriscourtin** [comment] 2017-04-28 18:30
"Resolved" by installing everything on Linux; works fine in that environment

Sent from my iPhone

On Apr 28, 2017, at 10:27 AM, mayork <notifications@github.com<mailto:notifications@github.com>> wrote:


@chriscourtin<https://github.com/chriscourtin> was this resolved?

**Comment by mayork** [comment] 2017-04-29 16:09
got it, closing issue for now

**Closed by mayork** 2017-04-29 16:09 UTC
